name: starch
services:
  typesense:
    image: typesense/typesense:27.1
    container_name: starch-typesense
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./tmp/typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    networks:
      - starch-network
  reading-parser:
    build: ./reading_parser
    container_name: starch-reading-parser
    restart: on-failure
    ports:
      - "3001:3001"
    volumes:
      - ./reading_parser:/app
    command: 'pnpm start'
    networks:
      - starch-network
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: 'bash -c "bundle install --verbose && bundle exec rails server -p 3000 -b 0.0.0.0"'
    networks:
      - starch-network
    tty: true

networks:
  starch-network:
