default: &default
  cleanup_session:
    class: CleanupSessionJob
    schedule: every day
  cleanup_verification_code:
    class: CleanupVerificationCodeJob
    schedule: every day

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default