default: &default
  sweep_authentication:
    class: SweepAuthenticationJob
    schedule: every day at midnight
  update_channels:
    class: UpdateChannelsJob
    schedule: every day at midnight
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default