default: &default
  sweep_authentication:
    class: SweepAuthenticationJob
    schedule: at 5am every day
  update_feeds:
    class: UpdateFeedsJob
    schedule: every day at midnight
  update_senders:
    class: UpdateEmailSendersJob
    schedule: every week at 1am
  cleanup_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches"
    schedule: every day at 9am
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
